### ISSUE TITLE
Improve scrolling in annotations window

### ISSUE THREAD

**Issue by davidskalinder** [davidskalinder/bpp-pass2-ui#8]
My mouse scroll wheel doesn't work inside Pass 1 Annotations window.  Mind you, I know this is the kind of thing that Access doesn't make it easy to change, so I realize we might be stuck with this.

Mentioning @johnklemke.

**Comment by johnklemke** [comment]
Yep, I looked into this when Morgan bumped into it -- it's a known deficiency of Access/VBA. It'd be a true pain to make it work....

**Comment by davidskalinder** [comment]
Yeah, I suspected as much.  Since GitHub has no way to explicitly classify issues as "Doomed", I guess I'll just close it...
